[1] API 타입 정의 1
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #10
Opened 2023-12-26 03:44 UTC by yjc2021

## :rocket: 주요 작업 내용
아래 도메인의 api들에 대한 타이핑을 작성했습니다
- login
- signup
- logout
- auth-user
- users
- settings
- channels
- posts
- likes

작성 과정에서 api 타입들에서 공통으로 사용되는 구조를 재사용하기 위해 `~/types/api/common.ts`파일을 생성했습니다
## :pushpin: 스크린샷
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/88219703/7b48ef06-8448-4d36-9218-0e3695326557)

## :white_check_mark: 고민 중인 부분 및 참고사항
- [ ] 네이밍 컨벤션이 적절한가요?
- [ ] 폴더 분리 및 타입 정의가 적절한가요? 

close #6

2023-12-26 04:25 UTC, bel1c10ud requested changes
고생 많으셨습니다. 
API 문서와 비교해봤는데 잘못 작성된 타입은 없는 것 같습니다. 🙂
🤔 다만 타입 네이밍은 파스칼 케이스로 통일하는 것이 맞는 것 같아요.

2023-12-26 04:25 UTC, bel1c10ud commented on src/types/api/posts.ts
> +export type createPostRequestType = FormData;
🤔 `FormData`의 타입을 자세하게 정의할 수 있으면 좋겠지만 `FormData`에는 제네릭을 사용할 수 없는 것 같네요
아래처럼 확장해서 사용할 수 있을지 알아보도록 하겠습니다.

(아마 `image`의 `Binary`는 `Base64`로 인코딩된 이미지가 내려올 것 같습니다.)

```ts
interface PostFormData extends FormData {
  title: string,
  image: string | null,
  channelId: string
}
```

2023-12-26 08:37 UTC, nnahyunn approved these changes
고생 많으셨습니다 용재님! 
더 수정할 부분은 안보이는 것 같습니다!

2023-12-27 00:22 UTC, bel1c10ud approved these changes

2023-12-27 00:22 UTC, merged