[13] 댓글, 알림, 검색 커스텀 훅 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #14
Opened 2023-12-27 05:39 UTC by nnahyunn

## 주요 작업 내용
댓글, 알림, 검색 커스텀 훅을 구현했습니다.
## 스크린샷
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/129164551/4c88c573-95f8-492a-aa15-348a394c1498)

## 고민 중인 부분 및 참고사항
- 에러메세지 컨벤션에 따라 예외처리가 잘 된건지 궁금합니다.
- api fetching하는 커스텀훅에 대한 제 이해가 맞는지 궁금합니다.
- 어떤 사항이든 반영하겠습니다.

close #13

2023-12-27 08:28 UTC, bel1c10ud requested changes
고생 많으셨습니다. 🙂
와일드 카드로 가져오는 타입의 네이밍과 `requset` 함수 적용하는 것만 반영해주시면 될 것 같아요.

2023-12-27 08:28 UTC, bel1c10ud commented on src/hooks/api/useComment.ts
> +import * as commentApiType from '~/types/api/comment';
컨벤션에 맞춰서 `CommentApiType`으로 수정하면 좋을 것 같아요 🙂

아래  `useNotification.ts`의 `notificationApiType`과 `useSearch.ts`의 `searchApiType`도 같이요.

2023-12-27 08:28 UTC, bel1c10ud commented on src/hooks/api/useComment.ts
> +        );
공통으로 사용하려고 만든 `request` 함수를 사용하면 좋을 것 같아요. 🙂
`requset` 함수는 인자로 `config`를 받는데 `config`에 `method: "get" | "post" | "delete"`를 넘겨서 용도에 맞게 사용할 수 있어요.

2023-12-27 17:30 UTC, yjc2021 requested changes
나현님 정말 수고하셨습니다!! 제가 api fetching custom hooks에 대해 더 설명을 드리고 업무를 드렸어야 했는데 너무 가이드라인을 제공 못 드린 점 죄송합니다. 
저희가 react-query (현 tanstack query)를 사용하지 말고, react-query가 하는 동작을 직접 custom hook에 녹여보자고 했기 때문에 api fetching을 담당하는 custom hook도 react query의 기능을 대략적으로 제공해야 합니다
현재 제가 예시로 든 커스텀 훅에는 다음 기능이 제공됩니다:
- fetching 상태에 따른 컴포넌트 UI 분기
- 이벤트 발생 시 실행되는 fetching 함수로 별도 제공
- api fetching 결과 data로 제공

더 많은 기능을 추가할 수 있겠지만 지금 가장 핵심적으로 필요한 기능을 적용해봤습니다. 또 굳이 각각의 커스텀 훅에서 status 상태를 관리하지 않고 연경님이 만드신 재사용 request 함수를 커스텀 훅으로 전환해서 status 상태를 이전시킬 수 있을 것 같습니다.

다른 팀원들도 의견 부탁드립니다.

2023-12-27 17:30 UTC, yjc2021 commented on src/hooks/api/useComment.ts
useComment.ts 파일을 comment 도메인의 각 api별로 분리하는 건 어떨까요: `src/hooks/api/comment/useCreateComment.ts`, `src/hooks/api/comment/useDeleteComment.ts`

이해를 돕기 위해 나현님 코드 바탕으로 useCreateComment.ts를 작성해봤습니다. 
```ts
// useCreateComment.ts
import { useState } from 'react';
import { request } from '~/api/axios';
import {
  CreateCommentRequestType,
  CreateCommentResponseType,
} from '~/types/api/comment';

export const useCreateComment = ({
  comment,
  postId,
}: CreateCommentRequestType) => {
  // const [isLoading, setIsLoading] = useState(false);
  // const [isError, setIsError] = useState(false);
  // const [isSuccess, setIsSuccess] = useState(false);

  // api fetching 진행 상태를 나태는 state입니다
  // status를 return해서 hook을 사용하는 컴포넌트에서 status에 따른 UI를 구분할 수 있습니다
  const [status, setStatus] = useState<
    'stale' | 'loading' | 'error' | 'success'
  >('stale');

  // api fetching 결과를 담는 state입니다
  // data를 return해서 hook을 사용하는 컴포넌트에서 api fetching 결과를 활용할 수 있습니다
  const [data, setData] = useState<CreateCommentResponseType | null>(null);
  const CREATE_COMMENT_URL = `/comments/create/${postId}`;

  // 사용자 인터랙션이 발생해야 실행되는 api fetching은 custom hook 내부에 함수를 정의하고 함수에 api fetching 로직을 넣습니다
  // createComment을 return해서 hook을 사용하는 컴포넌트의 이벤트 핸들러에 함수를 실행할 수 있습니다
  const createComment = async () => {
    try {
      setStatus('loading');
      const response = await request({
        method: 'POST',
        url: CREATE_COMMENT_URL,
        data: {
          comment,
          postId,
        },
      });

      setData(response);
      setStatus('success');
    } catch (e: unknown) {
      if (e instanceof Error) {
        console.error(`Comment: ${e.message} (createComment / ${postId})`);
      }
      setStatus('error');
    }
  };

  return { status, data, createComment };
};

export default useCreateComment;

```

2023-12-27 17:34 UTC, yjc2021 commented on src/hooks/api/useComment.ts
> +        console.error(`Comment: ${e.message} (createComment / ${postId})`);
error 형식을 만들어주는 util 모듈을 만들어도 좋을 것 같습니다

2023-12-30 04:07 UTC, bel1c10ud approved these changes
고생 많으셨습니다. 🙂
에러 핸들링을 `handleError` 함수로 분리해서 처리하신 부분 좋은 방법 같아요.
토큰 로직은 `axios` 인터셉터에서 처리하고 있어서 제거해도 될 것 같아요.

2023-12-30 04:07 UTC, bel1c10ud commented on src/utils/handleError.ts
> +};
유틸 함수 작성해서 분리한 것 좋은 것 같습니다. 👍 
유용하게 잘 사용할 것 같아요. 🙂

2023-12-30 04:07 UTC, bel1c10ud commented on src/hooks/api/comment/useCreateComment.ts
> +      });
이미 `request` 인스턴스에 등록된 인터셉터에서 처리하고 있는 부분이라 제거해도 될 것 같아요. 🤔

2023-12-30 04:07 UTC, bel1c10ud commented on src/hooks/api/search/useSearchAll.ts
> +  };
API 문서를 확인해보니 `Search`쪽 API는 요청 가능한 것 같아요. 🙂

2023-12-31 08:02 UTC, nnahyunn commented on src/hooks/api/comment/useCreateComment.ts
> +      });
pull을 늦게 받는 바람에 axios인터셉터 부분을 확인못해서 중복해서 작성해버렸네요🥲 제거 했습니다😊

2024-01-01 01:40 UTC, yjc2021 approved these changes

2024-01-01 01:53 UTC, merged