[37] Skeleton 재사용 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #39
Opened 2024-01-02 03:32 UTC by bel1c10ud

## :rocket: 주요 작업 내용
- Skeleton 컴포넌트를 구현하였습니다.
- CSS 애니메이션을 적용하였습니다.
- storybook story를 작성하였습니다.

## :pushpin: 스크린샷
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/1d413195-e972-4b56-b19a-b7a398a1d984)
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/7a216847-5f68-46a0-bbcc-a330e456baa9)

## :white_check_mark: 고민 중인 부분 및 참고사항
- [ ] `circle`이 `ture`인 경우 `width`와 `height`중 큰 값을 `width`와 `height` 양쪽에 반영 후, 해당 값의 절반을 `border-radius`로 설정합니다.
혹시 더 좋은 방법이 있다면 알려주세요 🙂
- [ ] CSS 애니메이션을 적용하였습니다. 적절한지 확인부탁드립니다. 🙂

close #37

2024-01-02 12:31 UTC, yjc2021 approved these changes
종운님 수고하셨습니다!

2024-01-02 12:31 UTC, yjc2021 commented on src/components/common/Skeleton.tsx
> +  width?: Property.Width;
width를 Property.Width로 했을 때 string으로 타이핑했을 때보다 장점이 무엇인지 궁금합니다! 
아래 '10rem' 처럼 rem이 붙어있는 값끼리 대소비교가 되던데 Property.Width, Property.Height로 타입을 정의하셔서 그런것인가요? 아니면 단순 string과 string의 대소비교인가요?

2024-01-02 12:31 UTC, yjc2021 commented on src/components/common/Skeleton.tsx
> +  mr?: Property.MarginRight;
padding, margin관련 props가 앞으로도 반복될 것 같아서 이를 재사용할 수 있는 공통 interface로 정의하고 컴포넌트들에서 extends하는 방식은 어떨까요?

2024-01-02 12:31 UTC, yjc2021 commented on src/components/common/Skeleton.tsx
> +  animation-play-state: ${(props) => (props.animation ? 'running' : 'pasued')};
animation 짱 이쁩니다 👏

2024-01-03 03:25 UTC, yeon-kk requested changes
상세하게 구성하신 부분 대단합니다 👍

2024-01-03 03:25 UTC, yeon-kk commented on src/components/common/Skeleton.stories.tsx
> +    height: '1rem',
프로젝트 단위기 rem으로 통일되어서, 입력할 때 단위를 포함하지 않고 숫자만 입력되는 방법도 좋을 것 같아요.

2024-01-03 03:39 UTC, bel1c10ud commented on src/components/common/Skeleton.stories.tsx
> +    height: '1rem',
맞아요, 사이즈 부분은 단위 없는 rem으로 통합할 예정입니다. 🙂 
수정 후 다시 한번 리뷰 요청 드릴게요. 👍

2024-01-03 03:42 UTC, bel1c10ud commented on src/components/common/Skeleton.tsx
> +  mr?: Property.MarginRight;
맞아요, 저도 불편해서 빠른 시일 내에 가능한지 테스트해보고 반영하겠습니다. 🙂
실질적으로 `styled-component`에서 `props`를 받아 처리하는 부분까지 공통 코드를 만들어 적용해야 될 것 같아요 🤔

2024-01-03 03:48 UTC, bel1c10ud commented on src/components/common/Skeleton.tsx
> +  width?: Property.Width;
`Property.Width`를 사용한다고 해서 `width`에 적용한 가능한 값만 허용한다거나 하는 식으로 동작하진 않더라구요.
(`auto`나 `fit-content`같은 몇 가지 속성과 `string`을 허용하는 유니온 타입으로 되어있습니다.)

대소비교는 `css`의 `max`, `min` 함수를 사용했습니다.

사이즈는 전부 단위 없는 `rem`으로 리펙토링 후 merge할 예정입니다.

2024-01-06 06:03 UTC, yeon-kk approved these changes

2024-01-06 06:43 UTC, merged