[36] Radio Button 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #48
Opened 2024-01-02 15:12 UTC by jiheeshin27

## :rocket: 주요 작업 내용
- Radio Button 컴포넌트를 구현했습니다. 
- Container, Flex, Text 컴포넌트를 반영했습니다.
## :pushpin: 스크린샷
<img width="838" alt="스크린샷 2024-01-03 오전 12 07 46" src="https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/62047243/06f52f89-5c99-42f7-ad6b-2bd604ce28fa">

## :white_check_mark: 고민 중인 부분 및 참고사항
- [ ] 각 RadioGroup마다 아래 적혀있는 label 내용이 다른데 현재는 해당 label을 props로 받아오게 구현했습니다. 방법이 적절한지 궁금합니다. 
- [ ] 기타 수정할 점을 알려주시면 감사하겠습니다. 
- [ ] Storybook에서 children에 대한 argTypes를 지정하는 것은 일반적으로 필요하지 않다고 해서 children에 대한 argTypes는 지정하지 않았습니다. 다른 의견이 있으신 분은 알려주세요!

close #36

2024-01-03 01:18 UTC, bel1c10ud requested changes
고생 많으셨습니다. 👍

2024-01-03 01:18 UTC, bel1c10ud commented on src/colors.css
> +  --radioGray: #59626b;
색상에 큰 차이가 없다면 기존에 선언해 놓은 것을 사용해주시고, 색상 수정이나 추가적으로 필요한 색상 말씀해주시면 의견 수렴해서 반영하도록 하겠습니다. 🙂

이 경우에는 `--adaptive500`이나 `--adaptive400`을 사용하면 될 것 같아요.

일관적인 색상과 다크모드 대응이나 타입 관리를 위한 부분이니 이해해주시면 감사하겠습니다. 🙇‍♂️

2024-01-03 01:18 UTC, bel1c10ud commented on src/components/RadioGroup/RadioGroup.tsx
> +}
`RadioGroup`에서 `labels`를 받아서 `Radio` 밑에 출력 해주게 되면 `Radio`와 `label`이 틀어져서 보이는 문제가 있어요.

![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/8cb97bdf-ffde-4288-9fd4-ca4f4b7f5f4a)

`Radio` 컴포넌트에서 직접 `label`을 출력해주면 해결될 것 같아요. 🙂

![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/c2e7c91c-0fe4-45a2-8e1c-d9911bdff831)

```tsx
// Radio.tsx
<Flex 
  as='fieldset'
  direction='column'
  alignItems='center'
  gap={1}
>
  <RadioButtonInput
    type='radio'
    value={value}
    name={name}
    defaultChecked={defaultChecked}
    disabled={disabled}
    checked={checked}
  ></RadioButtonInput>
  <Text as='label'>{children}</Text>
</Flex>
```

```tsx
// RadioGroup.tsx
<Container maxWidth='sm'>
  <Flex
    justifyContent='space-between'
    style={{ width: '33rem', height: '4.5rem' }}
  >
    {children}
  </Flex>
</Container>
```

2024-01-03 04:05 UTC, yeon-kk approved these changes
고생하셨습니다 지희님 👍

2024-01-04 01:31 UTC, jiheeshin27 commented on src/colors.css
> +  --radioGray: #59626b;
넵 반영하겠습니다 👍

2024-01-06 06:58 UTC, bel1c10ud approved these changes

2024-01-07 07:36 UTC, merged