[34] Loading 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #53
Opened 2024-01-03 01:51 UTC by yeon-kk

## :rocket: 주요 작업 내용
- Loading 컴포넌트를 구현했습니다.

## :pushpin: 스크린샷
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86847564/8b0c2c4b-9f93-4d46-b861-ad52ca27a1cf)

## :white_check_mark: 고민 중인 부분 및 참고사항
- [ ] size는 원의 크기를 나타냅니다. 2 이하의 값을 작성하면 2로 지정됩니다.
- [ ] time은 회전 속도를 나타냅니다. 숫자가 작아질수록 빠르게 회전합니다.
- [ ] primaryColor와 secondaryColor로 색상을 지정할 수 있습니다.

close #34

2024-01-03 09:54 UTC, yjc2021 requested changes
연경님 수고하셨습니다!

2024-01-03 09:54 UTC, yjc2021 commented on src/components/loading/CircleLoading.tsx
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/88219703/e12cece1-a5e4-4c15-8cf5-a6ed08b42b20)

size를 변경해도 loading의 두께가 변경되는 거 같지 않습니다. size변경을 두께에도 반영해야 할 것 같습니다. 너무 복잡하다면 그냥 size를 sm, lg 2개 정도의 토큰으로 제한하는 게 좋을 것 같습니다

2024-01-03 11:29 UTC, yeon-kk commented on src/components/loading/CircleLoading.tsx
stroke-width를 직접 변경할 수 있도록 수정했습니다

2024-01-04 03:29 UTC, bel1c10ud approved these changes
고생 많으셨습니다. 🙂
다양한 곳이 활용하기 좋을 것 같아요. 👍

2024-01-04 03:29 UTC, bel1c10ud commented on src/components/loading/CircleLoading.tsx
> +  secondaryColor?: ColorType;
`strokeWidth`는 조금 고민이 필요할 것 같은데, `primaryColor`와 `secondaryColor`는 아래와 같이 수정하면 어떨까요? 🤔
```js
stroke?: number;
color?: ColorType;
backgoundColor?: ColorType;
```

2024-01-04 03:29 UTC, bel1c10ud commented on src/components/loading/CircleLoading.tsx
> +    >
`Container`는 템플릿을 만들때 최상단을 감싸는 용도로 만든 컴포넌트라 이런용도로 사용하시기 불편하실 것 같아요. 🤔
빠른 시일 내에 단순 div 태그 용도로 사용할 수 있는 `Box` 컴포넌트를 추가하도록 하겠습니다. 🙇‍♂️

2024-01-05 00:26 UTC, yjc2021 approved these changes

2024-01-08 04:21 UTC, merged