[25] Input 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #54
Opened 2024-01-03 02:08 UTC by yeon-kk

## :rocket: 주요 작업 내용
- Input 컴포넌트를 구현했습니다

## :pushpin: 스크린샷
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86847564/9eb57d4c-d2d9-45e6-8f3f-81de46011838)
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86847564/468d4420-363a-4dff-a578-0653141d6909)
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86847564/561382b0-b6c6-4660-b5aa-9583039dd205)

## :white_check_mark: 고민 중인 부분 및 참고사항
-  onBlur되었을 때 올바른 입력인지 확인하는 로직은 추후 반영하겠습니다.
-  focus 상태에서 테두리에 하이라이트 되는 건 추후에 해보겠습니다.
- [ ] 각 input을 사용 목적에 따라 분리하는게 좋을까요?
- [ ] 에러 메시지 빨간색이 조금 더 밝아지면 좋을까요?

2024-01-04 00:32 UTC, yjc2021 requested changes
수고하셨습니다 연경님 👏

2024-01-04 00:32 UTC, yjc2021 commented on src/components/input/Input.tsx
> +      <Border>
혹시 Spacer없이 Border에 padding을 넣으면 결과가 달라질까요? 🤔 
만약 동일한 결과가 나온다면 추가적인 DOM 요소를 넣을 필요는 없을 것 같아요! :)

2024-01-04 00:32 UTC, yjc2021 commented on src/components/input/Input.tsx
> +            />
종운님 Button처럼 Input에도 Icon을 추가할 수 있으면 좋을 것 같습니다!
예를 들면 search bar의 오른쪽에 검색 icon이 있는 것처럼요!
Icon 컴포넌트를 선택적으로 children으로 받도록 구현하면 될 것 같아요 (종운님 Button 코드 참고하시면 될 것 같습니다) 👍

2024-01-04 00:32 UTC, yjc2021 commented on src/components/input/Input.tsx
> +  const InputField = styled.input`
styled component는 리액트 컴포넌트 외부에 정의해주셔야 합니다 :)
[공식문서](https://styled-components.com/docs/basics#define-styled-components-outside-of-the-render-method)에 자세한 이유가 나와있습니다

2024-01-04 00:32 UTC, yjc2021 commented on src/components/input/Input.tsx
> +
현재 컴포넌트에 Input에 입력한 값을 추적하는 로직이 없는 것 같습니다. Input 재사용 컴포넌트를 가져다 사용할 때, 결국 Input에 입력한 값을 가져와서 활용해야 하기 때문에 (ex. 로그인 id, pw 입력 후 submit 버튼 누르면 입력값으로 api 호출) 
props로 handleChange, (또는 handleBlur?) 등을 받아서 상위 컴포넌트에서 로직을 주입할 수 있게 만드셔야 할 것 같습니다 👍

2024-01-04 00:32 UTC, yjc2021 commented on src/components/input/Input.tsx
> +            <Text
Label을 Input 안에 넣는 것보다 Input border 밖에다 그리면 더 깔끔할 것 같습니다 :)

2024-01-04 00:32 UTC, yjc2021 commented on src/components/input/Input.tsx
> +import { Property } from 'csstype';
import 컨벤션대로 라이브러리 import을 저희가 만든 파일 import보다 먼저 해주세요:)

2024-01-04 00:38 UTC, yjc2021 commented on src/components/input/Input.tsx
> +const Input = ({
- input의 입력 text 크기를 선택하는 props가 없는 것 같습니다. 
- Input도 Button 처럼 필요한 크기가 다를 수 있어서 input 크기를 'sm' | 'md' | 'lg' 처럼 디자인 토큰화하는 것도 고민해 보시면 좋을 것 같습니다
(ex. 로그인 페이지에서 input은 'lg', 모달에서 input은 'sm', ...)

2024-01-04 04:03 UTC, bel1c10ud requested changes
고생 많으셨습니다. 👍

크기나 비율 고민 되시는 부분이 있으시면 질문 주셔도 되고, 재사용 컴포넌트들이 어느정도 완성되면 디자인 통일하는 작업을 할 예정이니 너무 부담 갖거나 고민하지 않으셔도 될 것 같아요. 🙂

2024-01-04 04:03 UTC, bel1c10ud commented on src/components/input/Input.tsx
> +}
`labelFontSize`, `labelFontWeight`, `labelFontColor`, `errorMessageFontColor`, `errorMessageFontSize`, `errorFontWeight`, `borderColor`, `backgroundColor`는 고정된 값을 사용할거라 커스텀 하지 않아도 될 것 같아요. 😢

만약에 커스텀이 필요하다면 용재님 말씀처럼 Input 전체에 대한 size(sm, md, lg) 옵션을 주고 label, input, message의 크기가 같이 변경 되면 될 것 같아요. 🤔 

`errorMessage`, `errorMessageFontColor` 같은 경우는 중립적인 의미를 가진 `message`, `messageColor` 정도의 이름을 변경하고, 여러 종류의 메시지를 사용하는 용도로 남겨 둘 수 있을 것 같아요. 🤔

```jsx
<Input 
  label=""
  placeholder=""
  message=""
  messageColor=""
>
 // ...
</Input>
```

2024-01-04 04:03 UTC, bel1c10ud commented on src/components/input/Input.tsx
> +  const InputField = styled.input`
label과 input의 시작점이 틀어져 보이는 문제가 있는데, input의 padding을 제거하거나 label과 input에 동일한 padding-left 값이 적용되면 해결 될 것 같습니다. 🤔

![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/192524ec-2cb7-485f-80b0-83000c620ff8)

저는 label과 input에 동일한 padding-left 값을 적용하는 방법을 추천드려요.

2024-01-04 04:03 UTC, bel1c10ud commented on src/components/input/Input.tsx
> +              type='text'
input의 type도 props로 받아야 할 것 같아요. 🤔

2024-01-05 01:53 UTC, yjc2021 approved these changes

2024-01-05 01:55 UTC, yjc2021 commented on src/stories/components/Input.stories.tsx
> +  },
control: 'string' 인 항목들을 control: 'text'로 바꿔주시면 좋을 것 같습니다

2024-01-06 07:02 UTC, bel1c10ud approved these changes

2024-01-06 10:14 UTC, merged