[43] PostCommentListItem 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #56
Opened 2024-01-03 02:38 UTC by yeon-kk

## :rocket: 주요 작업 내용
 PostCommentListItem 컴포넌트를 구현했습니다.

## :pushpin: 스크린샷
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86847564/e1c550ec-d5a0-4864-bfa5-57986d013ab1)

## :white_check_mark: 고민 중인 부분 및 참고사항

- [ ] 너비 지정에 대한 고민을 했습니다.
- [ ] avatar 부분은 교체하려고 합니다.
- [ ] avatar 영역과 textcontainer 영역이 서로 보존되도록 calc로 계산했는데, 값을 직접 하드코딩 한 부분이 마음에 걸립니다. 아바타 영역 값은 고정이고 gap 값도 고정이라고 생각했습니다. 하지만 컴포넌트 내부를 수정할 수는 있어서 수정이 필요하다면 하드코딩한 부분도 같이 수정해주어야 합니다.
- [ ] 폴더명 확인 부탁드립니다.

close #43

2024-01-05 02:10 UTC, bel1c10ud requested changes
고생 많으셨습니다. 👍

너비는 Flex를 사용하면 최종적으로 컴포넌트를 사용하는 쪽에서 지정해준 공간만큼 넓어질거라 깊게 고민하지 않으셔도 될 것 같아요. 🙂

2024-01-05 02:10 UTC, bel1c10ud commented on src/components/postComment/PostCommentListItem.tsx
> +  `;
`AvatarContainer`에 `flex-shrink: 0`을 주시면, `TextContainer`에 별도로 `width`를 설정하지 않아도 자동으로 남은 너비 전체를 사용해요.

![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/ad3ccbb4-8f8f-4ced-a61d-701295b849fc)


![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/f73cc880-1dac-48f1-acec-3d9a583166f2)

2024-01-05 02:10 UTC, bel1c10ud commented on src/components/postComment/PostCommentListItem.tsx
> +      <Spacer padding='0.75'>
Container는 템플릿 최상단을 감싸는 용도라 Flex를 사용하시는게 맞을 것 같아요. 🤔
이 부분은 혼동되기 쉬워서 빠른 시일내로 Box 컴포넌트를 추가하도록 하겠습니다.

그리고 별도로 Spacer 사용 안하셔도 Flex에 바로 padding을 적용하실 수 있어요. 🙂

```jsx
<Flex p={0.75}>
  //...
</Flex>
```

2024-01-05 02:22 UTC, yjc2021 requested changes
수고하셨습니다 연경님 😃

2024-01-05 02:22 UTC, yjc2021 commented on src/components/postComment/PostCommentListItem.tsx
> +  time: string;
POST api 모델을 참고하시면 created_at, updated_at 2가지 시간 정보가 있습니다
![image](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/88219703/c811415c-877b-4132-8dc8-574abb8bf356)

created_at만 있을 때 created_at을 사용하여 시간을 보여주고, updated_at이 만약 있다면 updated_at으로 시간을 교체하고 뒤에 '에 수정됨' 과 같은 UI가 있으면 좋을 것 같습니다
api 모델 속성명을 동일하게 가져가면 나중에 데이터 입력할 때 더 편하실 것 같아서 이 부분 참고만 해주세요 😄

2024-01-08 00:45 UTC, yeon-kk commented on src/components/postComment/PostCommentListItem.tsx
> +  `;
감사합니다 종운님 ! 👍

2024-01-11 03:52 UTC, yjc2021 approved these changes

2024-01-13 03:15 UTC, bel1c10ud approved these changes

2024-01-13 14:48 UTC, merged