[65] 파일 업로드 & 프로필 이미지 변경 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #66
Opened 2024-01-04 11:45 UTC by jiheeshin27

## :rocket: 주요 작업 내용
- 파일 업로드 기능 구현
- 프로필 이미지 변경 컴포넌트 구현
- 사진 업로드, 삭제, 취소, 저장 동작

## :pushpin: 스크린샷
<img width="854" alt="스크린샷 2024-01-04 오후 8 35 27" src="https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/62047243/69233ee7-cfb6-470c-b442-8bd9805a1e85">

## :white_check_mark: 고민 중인 부분 및 참고사항

- [ ] Button 컴포넌트를 사용하기 위해 label 안에 Button을 넣었는데, 이 경우 label과 input이 제대로 연결되지 않았습니다. 따라서 Button에 `as='span'`속성을 넣어주었는데 이에 따라 Button 컴포넌트의 propTypes를 변경해야 할 것 같아요. 아니면 다른 방법이 있는지 궁금합니다!
- [ ] '**사진 삭제**'를 했을 때 어떻게 처리해야 할지 고민됩니다.
제가 생각한 건 기본이미지값 주소를 `selectedImage`에 넣어주든지, 아니면 null로 넣어서 따로 처리를 할 건지.. 정도인데 다른 좋은 의견이 있다면 알려주세요!

2024-01-05 03:04 UTC, yjc2021 approved these changes
수고하셨습니다 지희님!
Modal 컴포넌트 구현이 늦어진 점 죄송합니다! Modal 컴포넌트로 전환은 제가 추후에 새 Issue로 만들어서 담당하겠습니다. 
Image 삭제 관련 의견 한 번 참고해보셔도 좋을 것 같습니다😃

2024-01-05 03:04 UTC, yjc2021 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +const CancelButton = styled.button`
CancelButton도 재사용 Button으로 만들 수 있을 거 같아요!

```ts
<Button
        variant='text'
        size='md'
        color='--adaptive500'
        onClick={handleClose}
        style={{
          width: '2.5rem',
          height: '2.5rem',
          borderRadius: '50%',
          padding: '0.125rem',
        }}
      >
```
처럼 인라인 스타일 쓰시면 될 것 같습니다 :)

2024-01-05 03:04 UTC, yjc2021 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
`  const [selectedImage, setSelectedImage] = useState<string | null>(currentImageUrl);` 은 어떨까요?
그러면 `handleDelete`에서 `setSelectedImage(null)`만 하고, Image src도 `selectedImage`로 변경해도 될 것 같아요.
현재 Image 컴포넌트에서 예외처리를 빼먹어서 이미지 삭제 시 검정색 화면이 나오는데 머지하시고 Image 수정하겠습니다

2024-01-05 03:04 UTC, yjc2021 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
![imageUpload](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/88219703/96cb071e-3d04-4da8-b9fb-5c3c31e75795)
위 방식으로 수정했을 때 결과입니다

2024-01-05 03:04 UTC, yjc2021 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +    // setSelectedImage(null);
setSelectedImage(null) 로 가셔도 될 것 같습니다 :)
(첫 리뷰 참고해주세요)

2024-01-05 03:04 UTC, yjc2021 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +            src={selectedImage || currentImageUrl}
src={selectedImage}로 수정하셔도 될 것 같습니다 :)
(첫 리뷰 참고해주세요)

2024-01-05 03:53 UTC, bel1c10ud requested changes
고생 많으셨습니다. 👍

이미지 제거 관련 로직은 아래 작성하긴했는데 [API 명세](https://school.programmers.co.kr/app/courses/19012/curriculum/lessons/255924#part-53253)를 보니까 원래 작성하신 방식도 괜찮은 것 같아요.

2024-01-05 03:53 UTC, bel1c10ud commented on src/components/uploadImage/ProfileImageUpload.tsx
> +            </label>
저는 input에 ref를 달고, Button을 클릭하면 `ref.current.click()`을 실행해서 파일 선택창이 열리는 방법을 생각했던 것 같아요. 🙂

```jsx
<Button onClick={() => inputRef.current?.click()} />
<input type="file" ref={inputRef} />
```

2024-01-05 03:53 UTC, bel1c10ud commented on src/components/uploadImage/ProfileImageUpload.tsx
> +        </Flex>
빠른 시일내에 width 100%와 height 100%를 props로 지정할 수 있게 수정하겠습니다. 🙇‍♂️

2024-01-05 03:53 UTC, bel1c10ud commented on src/components/uploadImage/ProfileImageUpload.tsx
> +  };
이미지 삭제 여부를 저장할 `isClear` state를 추가하고, 삭제 버튼을 눌렀을 때 `isClear`를 `true`로 변경하고, `input`이 변경되었을때 `isClear`를 `false`로 변경하는 방법은 어떨까요? 🤔

대신 이미지를 보여주는 쪽에서는 isClear가 true일때 'https://via.placeholder.com/200X200?text=brewers'를 보여주면 될 것 같아요.

2024-01-05 03:53 UTC, bel1c10ud commented on src/components/uploadImage/ProfileImageUpload.tsx
> +  onImageChange: (url: string) => void;
내부적에서 호출되는 방식이나 아래 onCancel prop을 생각해봤을 때 onSave라는 명칭이 더 잘 어울릴 것 같아요. 🤔

2024-01-05 03:53 UTC, bel1c10ud commented on src/components/uploadImage/ProfileImageUpload.tsx
> +          >
`margin-left`는 플랙스에 `ml` prop으로 지정할 수 있어요. 🙂

```jsx
<Flex direction="column" ml={1} />
```

2024-01-07 08:26 UTC, jiheeshin27 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +            src={selectedImage || currentImageUrl}
수정 완료했습니다! Image 컴포넌트에서 src에 null이 들어갈 수 있으니 PropsType 변경이 필요할 것 같아요!

2024-01-07 08:36 UTC, jiheeshin27 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +  };
용재님께서 Image컴포넌트 예외처리를 해주신다 해서 일단 용재님 방안으로 리팩토링 진행했습니다! 
이미지 삭제 후 저장시 selectedImage를 상위 컴포넌트로 넘겨서 처리하는 방식으로 구현해서 selectedImage을 바로 변경하는 방식을 선택했습니다 😀

2024-01-07 08:38 UTC, jiheeshin27 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +          >
감사합니다! 반영하겠습니다 👍

2024-01-07 08:40 UTC, jiheeshin27 commented on src/components/uploadImage/ProfileImageUpload.tsx
> +  onImageChange: (url: string) => void;
수정했습니다! 😀

2024-01-07 12:41 UTC, yjc2021 approved these changes
수고하셨습니다 지희님 👍

2024-01-08 09:56 UTC, bel1c10ud approved these changes

2024-01-08 12:15 UTC, merged