[57] Tab 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #67
Opened 2024-01-04 12:20 UTC by yjc2021

## :rocket: 주요 작업 내용
Tab 컴포넌트를 구현했습니다

## :pushpin: 스크린샷
![tab](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/88219703/fc471c7f-6031-4352-8adb-67666ac81366)

## :white_check_mark: 고민 중인 부분 및 참고사항

- ContextAPI, CompoundComponent 기법을 활용하여 구현했습니다
- Tabs는 기본적으로 부모 컴포넌트 width 전체를 차지합니다
- isFull props를 통해 TabItem들이 Tab을 꽉 채울지 (flex-grow: 1), width를 유지할지 선택할 수 있습니다
- gap props를 통해 TabItem 사이의 gap을 지정할 수 있습니다 
- fontSize를 통해 TabItem의 textSize를 선택할 수 있습니다 (단위: FONT_SIZE)
- fontWeight를 통해 TabItem의 textWeight를 선택할 수 있습니다 (단위: FONT_WEIGHT)
- defaultId를 통해 기본으로 선택할 TabItem을 선택할 수 있습니다

- Tabs.Item은 text props로 텍스트를 설정할 수 있습니다
- Tabs.Item은 handleClick props로 클릭 이벤트 핸들러를 추가할 수 있습니다
- Tabs.Item의 id와 Tabs.Body의 id props는 대응됩니다. 즉, 특정 id의 TabItem을 클릭하면 동일 값의 id를 가지는 TabBody를 그립니다 (동일 id 없으면 TabBody를 못 그립니다)

- [ ] 빠진 UI 사항 또는 로직이 있는지 궁금합니다
- [ ] 현재는 Tabs 컴포넌트 내부에서 선택된 tabId를 저장하는 state을 정의했습니다. 그런데 실제 사용할 때는 외부에서 state 및 setState 함수를 props로 받아와서 ContextProvider에 주입해야 할까요? 같이 고민하고 의견주시면 감사하겠습니다 :)
Closes #57

2024-01-05 04:50 UTC, bel1c10ud requested changes
고생 많으셨습니다. 👍

- 지금 시점에서는 추가할 로직은 없는 것 같아요.
- defaultId로 초깃값을 지정해주고, context를 통해 setSelectedId를 노출해주고 해당 메서드로 컨트롤 하는 정도면 충분하지 않을까 싶어요.

2024-01-05 04:50 UTC, bel1c10ud commented on src/components/common/Tabs/TabItem.tsx
> +const TabItemStyle = styled.button<{
Icon에 색상을 지정하지 않으면 기본적으로 상위 요소들의 color를 참고하는데, TabItemStyle 내부에서 color를 토글해주면 아래 처럼 아이콘 색상까지 제어 할 수 있어요.

```
color: ${({ $selected }) =>
  $selected ? 'var(--primaryColor)' : 'var(--adaptive400)'};
```

![chrome_Veb6DGHgOG](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/0b5b2359-e70c-42eb-b430-5360a784e97a)

2024-01-06 05:54 UTC, yeon-kk approved these changes
고생하셨습니다 용재님 👍 리뷰가 늦어져서 죄송합니다.

컴포넌트에서 몇번째 탭인지 상태만 관리한다면 지금 방법도 괜찮은 것 같아요

2024-01-06 05:54 UTC, yeon-kk commented on src/hooks/useDelayUnmount.ts
> +  useEffect(() => {
선언부와 구분되도록 한 줄 여백을 주면 가독성이 좋아질 것 같아요

2024-01-06 05:54 UTC, yeon-kk commented on src/components/common/Tabs/TabBody.tsx
> +};
```
if ( selectedId !== id ) {
  return null; }

return (<AnimatedContainer ... style={{display: 'block'}} ... > ...  </AnimatedContainer>)

```

이렇게 작성했을 때 같은 동작을 한다면 body id에 따라서 화면에 나타날 때와 그렇지 않을 때를 구분하기 좋을 수도 있을 것 같아요

2024-01-07 11:21 UTC, merged