[70] 피드 List Item 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #71
Opened 2024-01-04 18:56 UTC by jiheeshin27

## :rocket: 주요 작업 내용
- 피드의 List Item 컴포넌트를 구현했습니다. 
- 사용자 사진 클릭 시 props로 받아온 `onUserClick`을 호출합니다. 
- 피드 클릭 시 props로 받아온 `onFeedClick`을 호출합니다. 

## :pushpin: 스크린샷
<img width="1091" alt="스크린샷 2024-01-05 오전 3 54 13" src="https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/62047243/36380225-0b3f-46c5-a227-a69de54719bb">

## :white_check_mark: 고민 중인 부분 및 참고사항

- [ ] 좋아요 수와 댓글 수 아이콘
- [ ] props로 받아오는 것들을 한번씩 검토해주시면 좋겠습니다. 

Closes #70

2024-01-05 03:38 UTC, yjc2021 requested changes
수고하셨습니다 지희님 👏

2024-01-05 03:38 UTC, yjc2021 commented on src/components/feed/FeedFooterItem.tsx
> +  iconImg: string;
Icon 컴포넌트를 사용하시는 게 더 좋을 것 같습니다! 
대신 Icon컴포넌트는 props로 이름을 받아와서 사용할 수는 없고, 
1.  props로 Icon 컴포넌트 자체를 가져오거나, 
2. CompoundComponent로 상위에서 FeedFooter의 레이아웃을 구성할 수 있을 것 같습니다.
3. type을 props로 넘기고 (like, comment) Item 내부에서 조건적으로 대응하는 Icon을 가져와도 될 것 같습니다
```ts
type === 'like' ? <IconOOO> : <IconOOO>
```

2024-01-05 03:38 UTC, yjc2021 commented on src/components/feed/FeedFooterItem.tsx
> +      style={{ marginRight: '1rem' }}
P5
Flex 컴포넌트의 `mr` props를 넘겨주시면 marginRIght을 설정할 수 있습니다. (참고해주세용)
인라인 스타일도 괜찮아요! 👏

2024-01-05 03:38 UTC, yjc2021 commented on src/components/feed/FeedListItem.tsx
> +  date,
Post API 모델을 보면 created_at, updated_at으로 시간 관련 data가 2개가 존재합니다
updated_at이 없을 때는 created_at으로 date을 그리고, updated_at이 있으면 updated_at으로 시간을 그리고 뒤에 "수정됨" UI를 넣으면 좋을 것 같습니다.

2024-01-05 03:38 UTC, yjc2021 commented on src/components/feed/FeedListItem.tsx
P5
FeedItem hover 시 twitter처럼 미세하게 배경색을 바꿔도 좋을 것 같습니다:)

2024-01-05 03:43 UTC, yeon-kk approved these changes
고생 많으셨습니다 지희님 👍 

피드 이미지를 불러올 때 본문 이미지 레이아웃이 깜빡이는 것 같아요. 대체 이미지의 크기가 조절되면 좋을 것 같은데.. 방법이 있을지 생각해보겠습니다

2024-01-05 03:43 UTC, yeon-kk commented on src/components/feed/FeedFooterItem.tsx
> +  iconImg: string;
props 타입 네이밍 형식에 따라서 FeedFooterItemPropsType로 수정해주셔도 좋을 것 같아요

2024-01-05 03:43 UTC, yeon-kk commented on src/components/feed/FeedFooterItem.tsx
> +      ></Image>
alt에 '좋아요', '댓글'과 같이 명시적으로 작성해주는 것도 좋을 것 같아서, alt를 prop으로 받아도 좋을 것 같아요

2024-01-07 11:30 UTC, yjc2021 approved these changes
지희님 피드백 반영하느라 수고 많으셨습니다 :) Avatar 컴포넌트로만 변경해주시면 완벽할 것 같아요 👏

2024-01-07 11:30 UTC, yjc2021 commented on src/components/feed/FeedListItem.tsx
> +          <Image
지희님 Avatar 컴포넌트로 변경해주시면 좋을 것 같습니다 :)

2024-01-07 11:49 UTC, jiheeshin27 commented on src/components/feed/FeedListItem.tsx
> +          <Image
앗 Avatar로 변경하는 걸 위에 적어놓고 수정을 못했네요 바로 수정하겠습니다!!

2024-01-07 13:08 UTC, merged