[85] Input 컴포넌트 Refactor
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #88
Opened 2024-01-08 03:41 UTC by yeon-kk

## :rocket: 주요 작업 내용
1. onBlur를 삭제했습니다.
2. 사용자가 입력하고 debounce 이후 상태가 변하면, useEffect에서 유효성 검사 함수가 실행됩니다. 함수 분리를 고민하면서 useEffect에서 실행되도록 작성했습니다.
4. 유효성 검사 함수를 props로 전달받습니다.
5. debounce에서 onChange를 분리했습니다.
6. 유효성 검사 함수를 utils함수로 분리했습니다.
7. 이메일 유효성 검사 pattern 문자열을 constants 폴더에 추가했습니다.

## :pushpin: 스크린샷

## :white_check_mark: 고민 중인 부분 및 참고사항

- [ ] validation 함수명, constants폴더와 utils의 regex 파일에 있는 함수, 객체 네이밍 확인 부탁드립니다
- [ ] 이메일 유효성 검사의 경우에 어떤 범위까지 검사하면 좋을까요?

2024-01-10 02:37 UTC, yjc2021 requested changes
수고하셨습니다 :) 
네이밍만 수정해주시면 좋을 것 같습니다 👍

2024-01-10 02:37 UTC, yjc2021 commented on src/utils/regex.ts
함수 네이밍은 동사 + 명사로 해주시면 좋을 것 같습니다 :)

testRegex 정도면 될 것 같습니다 (useRegex는 훅 이름 같아서 제외했습니다)

2024-01-10 02:37 UTC, yjc2021 commented on src/stories/components/Input.stories.tsx
> +  const validation = (text: string) => {
네이밍은 동사+명사로 수정해주시면 좋을 것 같습니다. 
validateInput, validateText 등으로 하시면 될 것 같아요 :)

2024-01-11 03:52 UTC, yjc2021 approved these changes

2024-01-11 04:10 UTC, bel1c10ud approved these changes
고생 많으셨습니다.

2024-01-11 07:51 UTC, merged