[3] axios 공통으로 사용되는 request 함수 추가
prgrms-fe-devcourse/FEDC5_brewers_hyunju pull request #9
Opened 2023-12-26 02:14 UTC by yeon-kk

## :rocket: 주요 작업 내용
- [x] config 타입
- [x] request 메서드 사용
- [x] response status 200번대인 경우 응답 값 반환
- [x] try-catch
- [x] constants 폴더 생성
- [x] 응답 에러 메시지 추가

## :pushpin: 스크린샷

## :white_check_mark: 고민 중인 부분 및 참고사항
- [ ] error message 객체 리터럴 내부의 변수명 대소문자 확인 부탁드립니다.
- [ ] instance request 메서드 config 확인 부탁드립니다.
- [ ] 200번대의 경우에 return response.data를 하고있는데, 적절한지 궁금합니다.
- [ ] 추가적인 에러에 관한 조건문을 고민하고 있습니다.

close #3

2023-12-26 02:58 UTC, yjc2021 requested changes
고생하셨습니다 연경님! 공통 모듈이라 부담이 크셨을 텐데 정말 잘 구현해 주신 것 같습니다 :) 저희 api가 항상 content-type이 같지는 않아서 
1. 함수 매개변수로 type을 받아서 상황을 분기를 하거나 
2. 그냥 모두 config로 매번 작성하게 해야 할 것 같아요!
조금 더 고민해보시고 연경님이 더 낫다고 보는 방식으로 수정해주시면 될 것 같습니다. 
수고하셨습니다

2023-12-26 02:58 UTC, yjc2021 commented on src/api/axios.ts
> +      headers: { 'Content-Type': 'application/json' },
일부 api는 formData를 request body에 전달하는데 이때 'Content-Type'을 `multipart/form-data`로 수정해야 합니다. 그래서 headers를 고정으로 두면 안 될 것 같습니다.

2023-12-26 02:58 UTC, yjc2021 commented on src/api/axios.ts
> +    console.error(error);
` if (e instanceof Error) {}` 로 제한해도 괜찮을 것 같습니다.

2023-12-26 03:32 UTC, bel1c10ud approved these changes
고생 많으셨습니다. 고민하고 계신 부분에 코멘트 남겼습니다.

2023-12-26 03:32 UTC, bel1c10ud commented on src/api/axios.ts
> +    }
가독성 측면에서 아래와 같은 방식은 어떨까요? 🤔

```js
if (response.status >= 200 && response.status <= 299) {
  return response.data;
} else {
  throw new Error(ERROR_MESSAGES.API_REQUEST_ERROR);
}
```

```js
if (response.status >= 200 && response.status <= 299)
  return response.data;
else
  throw new Error(ERROR_MESSAGES.API_REQUEST_ERROR);
```

```js
if(response.status < 200 || response.status > 299) {
  throw new Error(ERROR_MESSAGES.API_REQUEST_ERROR);
}

return response.data;
```

2023-12-26 03:32 UTC, bel1c10ud commented on src/api/axios.ts
> +  }
저도 이번에 알게 되었는데 `catch` 안에서 `if(error instance Error)`로 타입 가드를 활용해서 좁혀서 
`Error` 객체인 경우 `Error` 객체의 `message`를 출력하고 아닌 경우는 그에 대한 예외 처리를 할 수 있는 것 같아요. 🙂

저는 `catch`로 들어오는 `Error` 객체의 이름을 무의식적으로 `e`로 작성을 했는데 한번 상의해 볼 필요가 있을 것 같아요. 🤔

2023-12-26 03:32 UTC, bel1c10ud commented on src/api/axios.ts
> +    });
저는 기본 값을 `config`로 덮어 쓴다는 개념으로 접근해서, 기본 옵션들을 상단에 작성하고 `...config`를 가장 하단에 작성했던 것 같은데, 다른 분들의 의견을 추가로 들어봐야 할 것 같아요. 🤔

```js
const response = await axiosInstance.request({
  headers: { 'Content-Type': 'application/json' },
  ...config,
});
```

2023-12-26 03:32 UTC, bel1c10ud commented on src/constants/error.ts
> +};
파일명을 `message.ts`로 가져가고 
아래처럼 도메인별로 객체를 정의하는 방법도 있을 것 같은데, 괜찮은 방법이 떠오르지 않네요. 🤔 

```js
export const API = {
  REQUEST_ERROR: 'API request error'
}
```

2023-12-27 00:25 UTC, yjc2021 approved these changes

2023-12-27 00:39 UTC, merged